spring:
  liquibase:
    change-log: classpath:database/master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    show-sql: true

